### PR TITLE
Linux-support

### LINKED ISSUE #19: Nothing working on linux.
I am using Linux (Ubuntu) and installed the extension. I can see that it took 7ms to start up.
But when trying to open a file in the file explorer using the context menu, nothing happens.
No notification pops up, no program starts, there is no message in the logs and in vscode's debug console either.

The package `opn@4` works using Node.js on my machine.

### PR DESCRIPTION
**Pull request by msundvick**
FIxes #19 (hopefully).
I'm not entirely sure why things didn't work on linux previously. But I added a fallback to get the uri from the current tab, and also updated node/vscode to more recent versions.
Everything seems to work on linux now (also tested on windows).

### CODE REVIEW

**Comment by MaddyGuthridge** [comment]
I'm not a maintainer for this project, but this looks like a lot of changes that might not be needed just to get linux support working.
* Does the target ES version need to be bumped from 5 to 6?
* Does it need to increase the minimum VS Code version by that much (some places, such as universities don't update their software that often, so this could break compatibility for them)?
* Does Node need to be updated from v12 to v18?

It also looks like you've run a linter through the code, which makes it much more challenging to discern the actual changes from changes to formatting.

I'm not saying that these are bad changes in themselves - the new formatting looks far nicer, and Node 12 is EOL and should probably be moved away from. My concern is that having those changes within this particular PR mean that the maintainer may be less willing to consider the fixes, compared to if they were done as separate pull requests that could be considered by themselves.

**Comment by msundvick** [comment]
Sure, there's definitely some over-aggressive changes that could be more limited. I tried out several solutions, so some changes that were previously needed might not be anymore.
- Target ES version needs to be bumped only when using ESBuild (I think). This is to support the `...` operator. Could probably work around that though. ESBuild shrinks the package size massively, but it could be split into a different PR.
- We need the api for `vscode.window.tabGroups.activeTabGroup`. I took a guess at when this happened; I checked again, and I wasn't far off, the feature was added here https://code.visualstudio.com/updates/v1_67#_tab-api. I'll change it to that version. Unfortunately the hacks required to support older versions are probably not worth it, more info here https://github.com/microsoft/vscode/issues/133532.
- Probably not; again, things weren't working and I wanted something recent enough that I could follow the vscode documentation. I think here what stopped me is actually the packaging tool https://www.npmjs.com/package/@vscode/vsce now requiring node 14. So either we can use node 14, or we can use an old vsce version (which is deprecated).

I can roll back the linter changes easily enough.

I completely agree, less changes would be easier to merge. I'm happy to do more work to that end, if there's interest from the maintainer in getting this merged.

The most recent changes I've uploaded are hopefully less disruptive, there's not much more I can cut out.

**Comment by MaddyGuthridge** [comment]
Awesome! I hope this gets merged soon! It'll be great to finally have this extension work correctly for me!

**Comment by sandcastle** [comment]
LGTM

**Pull request merged**
